### ISSUE TITLE
저장 모달에서의 스타일 미적용 및 html 태그 code 드러남

### ISSUE THREAD

**Issue by lavi27** [NGuard-Security/security_console#12]
![IMG_5450](https://github.com/NGuard-Security/security_console/assets/62757958/ff5d6da8-6d56-4c3e-9d0a-c8ee074e5af0)
![Screenshot_20240108_125420_Chrome](https://github.com/NGuard-Security/security_console/assets/62757958/27e20660-3ff0-493b-8427-312fc59aa77d)

간헐적 증상 의심

**Comment by kms0219kms** [comment]
html 태그 드러남은 template 문법을 v-html 문법으로 바꿔 해결되었습니다.

**Comment by lavi27** [comment]
새로 리팩토링한 브랜치에서는 해당 현상이 발견되지 않았습니다
