### ISSUE TITLE
serverId를 URL을 통해 받는것이 아닌 localStorage에 저장해서 이용하기

### ISSUE THREAD

**Issue by lavi27** [NGuard-Security/security_console#15]
기존에는 serverId를 URL에 포함하여 전달해야 했고, 이를 추출해서 이용해야 헸기에 번거로웠습니다.
그러나 이미 서버 선택 페이지가 존재하고 또 NavBar에서 충분히 서버를 선택 가능한 만큼 굳이 그럴 필요도 없습니다.
그렇기에 차라리 URL 단축 + URL 변조를 통한 해킹을 방어하기 위해 localStorage에 serverId를 저장한 후에 이용하는 것이 좋을것 같습니다.

**Comment by kms0219kms** [comment]
사용자가 만약에 여러 탭을 사용할 경우, localStorage로 하면 세션이 꼬이는 문제가 발생할 수 있고,

sessionStorage를 사용해도 즐겨찾기 등 URL 직접 접근이나 새로고침 시 세션이 사라지는 문제가 생길 수 있습니다.

해킹의 경우 백엔드 단에서 검증을 처리하므로(since v3) 굳이 서버아이디 값을 숨길 필요는 없어보입니다.
